//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace D250113.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D250113.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string ChineseButtonContent {
            get {
                return ResourceManager.GetString("ChineseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string EnglishButtonContent {
            get {
                return ResourceManager.GetString("EnglishButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string enum_DiagonaLift_None {
            get {
                return ResourceManager.GetString("enum_DiagonaLift_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One 的本地化字符串。
        /// </summary>
        public static string enum_DiagonaLift_One {
            get {
                return ResourceManager.GetString("enum_DiagonaLift_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two 的本地化字符串。
        /// </summary>
        public static string enum_DiagonaLift_Two {
            get {
                return ResourceManager.GetString("enum_DiagonaLift_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @scarletNnn 的本地化字符串。
        /// </summary>
        public static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        public static string MessageCaption {
            get {
                return ResourceManager.GetString("MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a message from code behind. 的本地化字符串。
        /// </summary>
        public static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button 的本地化字符串。
        /// </summary>
        public static string MyButton_Content {
            get {
                return ResourceManager.GetString("MyButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 32 的本地化字符串。
        /// </summary>
        public static string MyButton_FontSize {
            get {
                return ResourceManager.GetString("MyButton_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToolTip 的本地化字符串。
        /// </summary>
        public static string MyButton_ToolTip {
            get {
                return ResourceManager.GetString("MyButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One 的本地化字符串。
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowMessageButtonContent 的本地化字符串。
        /// </summary>
        public static string ShowMessageButtonContent {
            get {
                return ResourceManager.GetString("ShowMessageButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two 的本地化字符串。
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Welcome to this demo software 的本地化字符串。
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPF I18N Demo 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
